name: Build on push or pull request

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 7 & 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: |
            7
            8
      - name: Install advancecomp
        run: sudo apt-get install advancecomp
      - name: Install strip-nondeterminism
        run: sudo apt-get install strip-nondeterminism
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build --scan --stacktrace --warning-mode all
      - name: Rezip built .jar files to remove directory entries
        run: bash removeDirectoryEntries.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
