name: Build on release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: 'v*neRd' # Push events to matching v*neRd

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 7 & 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: |
            7
            8
      - name: Install advancecomp
        run: sudo apt-get install advancecomp
      - name: Install strip-nondeterminism
        run: sudo apt-get install strip-nondeterminism
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true
      - name: Build with Gradle
        env:
          BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: ./gradlew build --scan --stacktrace --warning-mode all
      - name: Rezip built .jar files to remove directory entries
        env:
          BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
        run: bash removeDirectoryEntries.sh
      - name: Draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Draft release ${{ github.ref }}
          body: Replace this text with the description of this release!
          draft: true
          prerelease: false
          files: build/libs/*
