name: Build on release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: 'v*neRd' # Push events to matching v*neRd

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 7 & 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: |
          7
          8
    - name: Install advancecomp
      run: sudo apt-get install advancecomp
    - name: Install strip-nondeterminism
      run: sudo apt-get install strip-nondeterminism
    - name: Build with Gradle
      env:
        BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        cache-disabled: true
        arguments: build --scan --stacktrace --warning-mode all
    - name: Rezip build .jar files to remove directory entries
      run: bash removeDirectoryEntries.sh
    - name: Run strip-nondeterminism on built .jar files
      run: strip-nondeterminism build/libs/*.jar
    - name: Run advzip (-i 9999) on built .jar files
      run: advzip --shrink-insane -kzi 9999 -p build/libs/*.jar
    - name: Draft release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Draft release ${{ github.ref }}
        body: Replace this text with the description of this release!
        draft: true
        prerelease: false
        files: build/libs/*.jar
